name: mysql_client
description: Native MySQL client written in Dart. Tested with MySQL Percona Server (5.7, 8), MariaDB (10). Supports TLS.
version: 0.0.28
homepage: https://github.com/zim32/mysql.dart
repository: https://github.com/zim32/mysql.dart
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  buffer: ^1.2.0
  crypto: ^3.0.2
  tuple: ^2.0.1
  logger: ^1.3.0

dev_dependencies:
  hex: ^0.2.0
  lints: ^2.0.1
  test: ^1.24.1

